[package]
name = "toy"
version = "0.1.0"
authors = ["alex"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
svg = "^0.8.0"
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"